# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Spectrum_noise_analyze.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1273, 824)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 1241, 771))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.Ip_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Ip_input.setObjectName("Ip_input")
        self.horizontalLayout_4.addWidget(self.Ip_input)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_connect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_connect.setCheckable(True)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.horizontalLayout_4.addWidget(self.pushButton_connect)
        self.pushButton_Refresh = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")
        self.horizontalLayout_4.addWidget(self.pushButton_Refresh)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.lineEdit_Ymax = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_Ymax.setObjectName("lineEdit_Ymax")
        self.horizontalLayout_7.addWidget(self.lineEdit_Ymax)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pushButton_Enable = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Enable.setCheckable(True)
        self.pushButton_Enable.setObjectName("pushButton_Enable")
        self.horizontalLayout_7.addWidget(self.pushButton_Enable)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.B1_mean_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B1_mean_value.setObjectName("B1_mean_value")
        self.horizontalLayout_5.addWidget(self.B1_mean_value)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelxx = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelxx.setFont(font)
        self.labelxx.setObjectName("labelxx")
        self.horizontalLayout_8.addWidget(self.labelxx)
        self.B1_std_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B1_std_value.setObjectName("B1_std_value")
        self.horizontalLayout_8.addWidget(self.B1_std_value)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.xx = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.xx.setFont(font)
        self.xx.setObjectName("xx")
        self.horizontalLayout_9.addWidget(self.xx)
        self.B1_std_mean_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B1_std_mean_value.setObjectName("B1_std_mean_value")
        self.horizontalLayout_9.addWidget(self.B1_std_mean_value)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_14.addWidget(self.label_30)
        self.B2_mean_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B2_mean_value.setObjectName("B2_mean_value")
        self.horizontalLayout_14.addWidget(self.B2_mean_value)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_15.addWidget(self.label_32)
        self.B2_std_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B2_std_value.setObjectName("B2_std_value")
        self.horizontalLayout_15.addWidget(self.B2_std_value)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_13.addWidget(self.label_28)
        self.B2_std_mean_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B2_std_mean_value.setObjectName("B2_std_mean_value")
        self.horizontalLayout_13.addWidget(self.B2_std_mean_value)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.B1 = PlotWidget(self.verticalLayoutWidget)
        self.B1.setObjectName("B1")
        self.gridLayout_4.addWidget(self.B1, 0, 0, 1, 1)
        self.B2 = PlotWidget(self.verticalLayoutWidget)
        self.B2.setObjectName("B2")
        self.gridLayout_4.addWidget(self.B2, 0, 1, 1, 1)
        self.B2_std = PlotWidget(self.verticalLayoutWidget)
        self.B2_std.setObjectName("B2_std")
        self.gridLayout_4.addWidget(self.B2_std, 1, 1, 1, 1)
        self.B1_std = PlotWidget(self.verticalLayoutWidget)
        self.B1_std.setObjectName("B1_std")
        self.gridLayout_4.addWidget(self.B1_std, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.B4_mean_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B4_mean_value.setObjectName("B4_mean_value")
        self.horizontalLayout_16.addWidget(self.B4_mean_value)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labelxx_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelxx_2.setFont(font)
        self.labelxx_2.setObjectName("labelxx_2")
        self.horizontalLayout_17.addWidget(self.labelxx_2)
        self.B4_std_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B4_std_value.setObjectName("B4_std_value")
        self.horizontalLayout_17.addWidget(self.B4_std_value)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.xx_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.xx_2.setFont(font)
        self.xx_2.setObjectName("xx_2")
        self.horizontalLayout_18.addWidget(self.xx_2)
        self.B4_std_mean_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B4_std_mean_value.setObjectName("B4_std_mean_value")
        self.horizontalLayout_18.addWidget(self.B4_std_mean_value)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem13)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_18)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_19.addWidget(self.label_31)
        self.B3_mean_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B3_mean_value.setObjectName("B3_mean_value")
        self.horizontalLayout_19.addWidget(self.B3_mean_value)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem15)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_20.addWidget(self.label_33)
        self.B3_std_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B3_std_value.setObjectName("B3_std_value")
        self.horizontalLayout_20.addWidget(self.B3_std_value)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem16)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_21.addWidget(self.label_29)
        self.B3_std_mean_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.B3_std_mean_value.setObjectName("B3_std_mean_value")
        self.horizontalLayout_21.addWidget(self.B3_std_mean_value)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem17)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_21)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.B3 = PlotWidget(self.verticalLayoutWidget)
        self.B3.setObjectName("B3")
        self.gridLayout.addWidget(self.B3, 0, 0, 1, 1)
        self.B4 = PlotWidget(self.verticalLayoutWidget)
        self.B4.setObjectName("B4")
        self.gridLayout.addWidget(self.B4, 0, 1, 1, 1)
        self.B3_std = PlotWidget(self.verticalLayoutWidget)
        self.B3_std.setObjectName("B3_std")
        self.gridLayout.addWidget(self.B3_std, 1, 0, 1, 1)
        self.B4_std = PlotWidget(self.verticalLayoutWidget)
        self.B4_std.setObjectName("B4_std")
        self.gridLayout.addWidget(self.B4_std, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Ip_input.returnPressed.connect(self.pushButton_connect.click)
        self.lineEdit_Ymax.returnPressed.connect(self.pushButton_Enable.click)
        self.pushButton_Refresh.clicked.connect(MainWindow.STD_refresh)
        self.pushButton_Enable.toggled['bool'].connect(MainWindow.Ymax_enable)
        self.pushButton_connect.toggled['bool'].connect(MainWindow.user_connect_unit)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Unit IP"))
        self.Ip_input.setText(_translate("MainWindow", "172.16.3.1"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
        self.pushButton_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.label_9.setText(_translate("MainWindow", "Y Max:"))
        self.lineEdit_Ymax.setText(_translate("MainWindow", "3000"))
        self.pushButton_Enable.setText(_translate("MainWindow", "Enable"))
        self.label_12.setText(_translate("MainWindow", "B1:"))
        self.label_13.setText(_translate("MainWindow", "Mean:"))
        self.B1_mean_value.setText(_translate("MainWindow", "0"))
        self.labelxx.setText(_translate("MainWindow", "Std:"))
        self.B1_std_value.setText(_translate("MainWindow", "0"))
        self.xx.setText(_translate("MainWindow", "Std/Mean:"))
        self.B1_std_mean_value.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "B2:"))
        self.label_30.setText(_translate("MainWindow", "Mean:"))
        self.B2_mean_value.setText(_translate("MainWindow", "0"))
        self.label_32.setText(_translate("MainWindow", "Std:"))
        self.B2_std_value.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "Std/Mean:"))
        self.B2_std_mean_value.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "B4:"))
        self.label_15.setText(_translate("MainWindow", "Mean:"))
        self.B4_mean_value.setText(_translate("MainWindow", "0"))
        self.labelxx_2.setText(_translate("MainWindow", "Std:"))
        self.B4_std_value.setText(_translate("MainWindow", "0"))
        self.xx_2.setText(_translate("MainWindow", "Std/Mean:"))
        self.B4_std_mean_value.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "B3:"))
        self.label_31.setText(_translate("MainWindow", "Mean:"))
        self.B3_mean_value.setText(_translate("MainWindow", "0"))
        self.label_33.setText(_translate("MainWindow", "Std:"))
        self.B3_std_value.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "Std/Mean:"))
        self.B3_std_mean_value.setText(_translate("MainWindow", "0"))
from pyqtgraph import PlotWidget
